{% set name = "jenkspy" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 368ade0f55d0407977a52ddd9f5ef780cbd2867eb92d0b964de706bd70686736

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy

test:
  imports:
    - jenkspy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mthh/jenkspy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compute Natural Breaks (Fisher-Jenks algorithm)
  description: Compute natural breaks (Fisher-Jenks algorithm) on list/tuple/array/numpy.ndarray of integers/floats.
  dev_url: https://github.com/mthh/jenkspy
  doc_url: https://github.com/mthh/jenkspy

extra:
  recipe-maintainers:
    - mthh
