{% set name = "jenkspy" %}
{% set version = "0.2.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d14d70b3b8e353f5736a31c2ef048c9869c34f0452542866c1362d1cd924bbc1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - jenkspy

about:
  home: http://github.com/mthh/jenkspy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compute Natural Breaks (Jenks algorythm)
  description: "Compute natural break values (Jenks algorythm) on list/tuple/numpy.ndarray of integers/floats."
  dev_url: https://github.com/mthh/jenkspy

extra:
  recipe-maintainers:
    - nickp60
