travis:
  secure:
    BINSTAR_TOKEN: XQePgr5CyWpo9l7mYc4HKRcG6T9cOiJMAvqSVk+bg7j+QOERnbpFyuZKgLCA64OVUz7Qg8aKbl/8lvatMxzUnEf8mmrjd+XQDnXGLetI1MFh4yPxpKMWQoXakEE4UPtrxb3PSOSxN0VG6gTnLl6SoqUqDrTCSEYosw1tE0fKKeP9CLKjampzLyg2xSRe3aBegB+Efhzakki1wQ7S/Cjkar02KTxWAlPd4m9Ztp0bm9EjOnGEItxKyhz2MWN0aBqVIH/flqd6DKqnSIcgeAvA+/yktX/QwKqlnEcvHD8ukMu3mz5YDMDgqWSf/nsY72oSdnuNlL1F/76MAvhvRtB6LtNrrS8SOLoiioGzDS+DcUWwhPFzaLRa+VZyz5ZBUH6d5CMP6gOZYz1e8HlZ9FAN0P5m4AYeCYNLe3uk4h9zjeqIrH1INjx30T25JxKGgskHqbLxyFRqQGq97uVcCptNdlJTlZ1cQa5Wwkre6K55dK1FzMkaTbc+YOaIVTWVfzOQcc2Wy92oKEKNEnntQNywEtaysgKElI/ladsxgfcu/Czh5F+1gXKiDO55cuRMTNKZHTKeuQFL0DvOQCcrwQg4zXS9XeJPWW8aoDFTd3kTFcgVl1QGC/4CZhT6xqzAzTOmM8pgXy8csSUPxrCHIGYtngIaaYw2TiOCnDPVlqRSd7s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
