travis:
  secure:
    BINSTAR_TOKEN: LxdxFhNae7hmBX0kJsRc5HeTSvOjN+3nYt4Q9HUIBmytHQIkeVdJh1eeDnxtRTRBKBPSAaXGZaTpvp2KXmnbT/ofArrUUrh2UM69ZWNehv1D0W9WptF3jqx89u64IEErivySvdUkcLvAmDIQzxS/U8FTriLAXl1YnDP9aJYAxc01jMkEwc9Y05d0ck5JW20UAtoMA9lPhsKLHW0YzdWywr0EYcq5eRZ1b+4F1zcXzv1GZG9j5fIxE2MQepUsTAObmD8Y9mDYae/jqrj9rqYdpTKE/bHwX27rxDV+MNgTTPsSgEfVvUTDiwSljYMAIj99OuUIYMunVBbIrLeb7QghmiOVc/NiNW2EPxHbfnuW+ITX7guoLO3P3miUU/1J42ICWSGBF9hiMvQGCE5pozx1PKi9RUVa9oy+HHXeiEzvqXSJp5Em5qoKexAv5QNd6KDdezlBZOI+0OFrOA4YhlnSlQFgVBCIRQvmn0rL82rdLYSlyP5nlxWuBxIR1McL5JhFca3S0E8PuuNwcQnDo1crXsEnUDtnEiyESA45kLHGXMKM4cHYslmOllbRU8K32ertbexRmWK/CyxlZ6tdfPTIHiRmq45qF7iZ2/hCmpitSxbG48TyD04gPUKt1zwQjmHWOGbNtjmcUC7d0xo50JuZZgHwsKl7O0zFrk1pWeu7KbA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
