travis:
  secure:
    BINSTAR_TOKEN: VE24S9G0qS6YOfV0RX9RFgHuF7bWJPl08DGVNxrqgsRO1+6Qd5QlISWxk+s+WDYsW6isxOBk5ZcU7RhCPwK35hFHXSHDmEgqQFRkJuvDZddiSskqgDv4pfh/FBJBY/Ik1NQaZ3UbS+2j+4U8u0JigYXVJvcZsW1j/2Orb3z4IC7D0elwxRHaZy2JK8Own+CbU40T4IjA76bEx+VI7Ap5Q+EDdlNIHsaP28DzBj15VaG02MvYbdqC2RAcj0yLmSAZYWRKekrij47eDIBE5L0u097HxjDxG0eD0PycQVrsdek8qg+tifHPTb2khrGAGzdXXFAkja1oLNgedGuXoJjURtThY5daaeSbPwuMPIaAhjORPnZZH8BrffCTSOBsOfQ0gydwe9xNDSkoOlqoJhFalrfvzbpcpEVRiqKaXGG217bIod1YRJxkXn8zJSZ2wYSrGGNdra4QAIc8yShV72Zs7CcT763wRqkzvhZ4ludzK1Ywl/Angaw/D0ciuV2qERzdevVnSLgU0LnrdnTWyfPnYNifRtYva/jRIoc8QWvr8QyCEsd7fN/BK0q7qwdLqFQbgY4DNJXNmvqhcaxodRYpmEGxxvaNg686WmjZcHc37vSebJcktDcXKjXsnUNpLbOr3HX80f379TuURZB6PRWi8xpXERyRn8IumuFiIy4kMYU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
