travis:
  secure:
    BINSTAR_TOKEN: XEvuZlptccM9ff+eQRdVKoQe11yDrisKKzZx0murxGhRSQDKOOCO+vEBJaZvONmhNb/3VabynRUEvH94GPSw4ODXuBdgHKRRGYXJux+8le97JWVfa3sYw37XNKwXda8/1/oTUBk6lWJqb8akkktKJDtf+DoCYwMVmVATIqvXge4TI5DPFE/H6aip2jLFh9dxVE82evwwRmbHmW6BbtOjpWdfPmuDU4+JNTY6r7N/k9V8DocEtPTqbANLe2p6KeCmzKZk3Xo1b41L0OtW/k1oOLgeUhucWGFO9VNyHrP+I5v8sEsGh9xYzv6L3rwXHgcClQlhsrEZUlA4JZs959RPjD5XUq19gbUi2PhZFtA0jCfvZN1ucctSWH+W+uhWpYLOgkpVegjUDptn8gtFwrc9RSpfhtDA/BfUsIbjrwioJq3bXqvDJaro/a6nZjc8RkYHnNBSSmHJlBgFFwvSjhg4CiKDrHBKarqozmYWT5ZFgd0xKgUsGSXatLTBbQcuzal9bx3jo2jSjmGyu73KKBCbLzcydOzz+AfjA2VZ1sSVI+pMLLkLl1VnKdIUUo1TA1YmTj4oUcrTn60WQ0jx1CgVw3/6tswt1wm8P8lGoCCAD8TUXDtZbvbpXrlB6y/zHRmEn2NV4HPg4dmonvX7k9VIaizK55eP5YIvfEEmIbK0vM4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
