travis:
  secure:
    BINSTAR_TOKEN: LvYrVHGie7qmMZERKXTamK3LKhwDLycHpgYlkdBVha9qL5Z5Wu4ijlVjCMMh7hQ06KuuCBRMiVl4MaxLiQnrERdf2Lq+ZZjVMLxCLn0hMAHOnoyDrxRbSw63b/BmfPx3K1xH5kDMndqrmyxVqZfuSQbDsG//6xjg93OVFDcLNWtpKl/5IWBKKjKNiYVIkM9xeA4gkPHCDLRMEhKZ+n4GQJJRKWInqds8Zw4XWF2t7/crapckvC1FF6jZEdW6kl24H+JKK8glMbCVnm3Ad1Y+rRzMrxzbye6MkgaSADXTf7AUsE+4wQuJAeS+dtWwwfuAP7Nwk+i0hEWVucNV7q0l3LGg5ZOzNlRAjYRkLN9aBBXjLh/W8KVdCcNiBRTT4VUp/P7auW5TNF952YO8FqsW+UdOq9neXOue//uRmeplCky7X05aXu+pM2oaxzYK4WfQKZsktO7vjXdQjEcjLEAQr7jFMVFIekiDeZWBwgD3ZfD/D7D/DinIcmOyupff7jzdc76PlMVAnKM6Vmf5b9VH1x86OH8xGoa9xcE4pbcHXWd98fHjKaHXn+0Ob0Iqj8jYFeNp6qs3q5r103pDlDiFmrzIpCiwFGUQMQ5aybUyGCXUjJ9agKnA9lRkFg+LwyMSCtJvP5JiHN5qHNYXkRqVcwD0z2w5E2dpUW0+LeldK6g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
